version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdb-data:/var/lib/postgresql/data 

  polls:
    build: .
    command: gunicorn polling.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/polls
    image: polling-image
    container_name: polls
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  server:
    volumes:
      - static:/polls
    build: ./nginx
    ports: 
      - 80:80
    depends_on:
      - polls

volumes:
  pgdb-data:
    driver: local
  static:


      