FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
#WORKDIR /usr/src/
#COPY ./static/ ./
# - static:/polls/static/polls/
#  static:
#    - ./polls/static/polls/